name: Generate GitHub Stats

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate statistics
        uses: cicirello/user-statistician@master
        with:
          username: JoacoRy20
